### ISSUE TITLE
Typescript Difficulty

### ISSUE THREAD

**Issue by JQuinnie** [iAmWillShepherd/ama#2]
- What is the hardest part of learning typescript?
- Did you learn by the documentation/example or just from using it on your projects/work?
- If you have any good resources, please share, thanks!

**Comment by iAmWillShepherd** [comment]
> What is the hardest part of learning typescript?

For me, the hardest part of learning TypeScript has actually more to do with learning JavaScript. Before starting on Desktop, I had not touched JS in almost six years. 

> Did you learn from the documentation/example or just from using it on your projects/work?

If I were a better person, perhaps I would have taken some time to read the documentation on the TS website, but I learned by jumping straight into the project. TypeScript _borrows_ a lot from c#, so things weren’t completely unfamiliar. At the moment, the only thing I use TS for is GitHub Desktop. All of my personal projects are written in C/C++/C# or Julia.

> If you have any good resources, please share, thanks!

The [TypeScript](https://www.typescriptlang.org/docs/handbook/basic-types.html) documentation is a good place to start.
MDN's [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript) on JavaScript may be useful as well.

Most of my issues are not at the language level so I have not spent much time going over TS documentation save for [TS Advanced Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html)
